name: pr
on: [pull_request]
jobs:
  check-race:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - run: go version
      - run: sudo apt-get install redis-server
      - run: make deps
      - run: make check-race
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - run: go version
      - run: sudo apt-get install redis-server
      - run: make deps
      - run: make check-fmt
      - run: make vet
      - run: make staticcheck
      - run: make cicheck
  mixin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - run: go version
      - run: cd skipper-mixin; go install github.com/monitoring-mixins/mixtool/cmd/mixtool
      - run: cd skipper-mixin; go install github.com/google/go-jsonnet/cmd/jsonnetfmt
      - run: cd skipper-mixin; make lint build
